apiVersion: 1
datasources:
  - name: oneka
    type: influxdb
    access: proxy
    database: oneka
    user: oneka
    password: $INFLUX_PASS
    url: http://$INFLUX_HOST:8086
    isDefault: true
    editable: true