# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daqmessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='daqmessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61qmessage.proto\x1a\x0cnanopb.proto\"A\n\nAnalogChan\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\x0f\n\x07voltage\x18\x02 \x01(\x05\x12\x11\n\tdigitalIn\x18\x03 \x01(\x05\"#\n\x10\x44ifferentialChan\x12\x0f\n\x07voltage\x18\x01 \x01(\x05\"\xe5\x01\n\nDaqMessage\x12\x0f\n\x07\x62oardId\x18\x01 \x01(\x05\x12\x1d\n\x15powerSupplyVoltage_mV\x18\x02 \x01(\x05\x12\x1d\n\x15powerSupplyCurrent_mA\x18\x03 \x01(\x05\x12\x18\n\x10\x63hargeVoltage_mV\x18\x04 \x01(\x05\x12\x18\n\x10\x63hargeCurrent_mA\x18\x05 \x01(\x05\x12&\n\nanalogChan\x18\x06 \x03(\x0b\x32\x0b.AnalogChanB\x05\x92?\x02\x10\x14\x12,\n\x10\x64ifferentialChan\x18\x07 \x03(\x0b\x32\x0b.AnalogChanB\x05\x92?\x02\x10\x04\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_ANALOGCHAN = _descriptor.Descriptor(
  name='AnalogChan',
  full_name='AnalogChan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current', full_name='AnalogChan.current', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='AnalogChan.voltage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digitalIn', full_name='AnalogChan.digitalIn', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=99,
)


_DIFFERENTIALCHAN = _descriptor.Descriptor(
  name='DifferentialChan',
  full_name='DifferentialChan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage', full_name='DifferentialChan.voltage', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=136,
)


_DAQMESSAGE = _descriptor.Descriptor(
  name='DaqMessage',
  full_name='DaqMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='boardId', full_name='DaqMessage.boardId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='powerSupplyVoltage_mV', full_name='DaqMessage.powerSupplyVoltage_mV', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='powerSupplyCurrent_mA', full_name='DaqMessage.powerSupplyCurrent_mA', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargeVoltage_mV', full_name='DaqMessage.chargeVoltage_mV', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargeCurrent_mA', full_name='DaqMessage.chargeCurrent_mA', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='analogChan', full_name='DaqMessage.analogChan', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\024', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='differentialChan', full_name='DaqMessage.differentialChan', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\004', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=368,
)

_DAQMESSAGE.fields_by_name['analogChan'].message_type = _ANALOGCHAN
_DAQMESSAGE.fields_by_name['differentialChan'].message_type = _ANALOGCHAN
DESCRIPTOR.message_types_by_name['AnalogChan'] = _ANALOGCHAN
DESCRIPTOR.message_types_by_name['DifferentialChan'] = _DIFFERENTIALCHAN
DESCRIPTOR.message_types_by_name['DaqMessage'] = _DAQMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalogChan = _reflection.GeneratedProtocolMessageType('AnalogChan', (_message.Message,), {
  'DESCRIPTOR' : _ANALOGCHAN,
  '__module__' : 'daqmessage_pb2'
  # @@protoc_insertion_point(class_scope:AnalogChan)
  })
_sym_db.RegisterMessage(AnalogChan)

DifferentialChan = _reflection.GeneratedProtocolMessageType('DifferentialChan', (_message.Message,), {
  'DESCRIPTOR' : _DIFFERENTIALCHAN,
  '__module__' : 'daqmessage_pb2'
  # @@protoc_insertion_point(class_scope:DifferentialChan)
  })
_sym_db.RegisterMessage(DifferentialChan)

DaqMessage = _reflection.GeneratedProtocolMessageType('DaqMessage', (_message.Message,), {
  'DESCRIPTOR' : _DAQMESSAGE,
  '__module__' : 'daqmessage_pb2'
  # @@protoc_insertion_point(class_scope:DaqMessage)
  })
_sym_db.RegisterMessage(DaqMessage)


_DAQMESSAGE.fields_by_name['analogChan']._options = None
_DAQMESSAGE.fields_by_name['differentialChan']._options = None
# @@protoc_insertion_point(module_scope)
